-- Drop the existing media table
DROP TABLE media;

-- Create the media table with correct structure
CREATE TABLE media (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER, -- referință la tabela pets
    type VARCHAR2(50), -- Removed restrictive check constraint temporarily
    url VARCHAR2(255), -- adresa URL a fișierului media
    upload_date DATE DEFAULT SYSDATE, -- data încărcării fișierului media
    CONSTRAINT fk_media FOREIGN KEY (pet_id) REFERENCES pets(id)
); 