CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    surname VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    location VARCHAR2(255),
    is_family NUMBER(1) DEFAULT 0, -- 0 = false, 1 = true
    latitude NUMBER(10, 8),
    longitude NUMBER(11, 8),
    rol VARCHAR2(50)
);

CREATE TABLE pets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    species VARCHAR2(50) NOT NULL,
    breed VARCHAR2(100),
    age NUMBER(3), -- vârsta poate fi de maxim 999 ani
    gender VARCHAR2(10), -- "Male", "Female"
    health_status VARCHAR2(100),
    description VARCHAR2(1000),
    available_for_adoption NUMBER(1) DEFAULT 0, -- 0 = false, 1 = true
    adoption_address VARCHAR2(255),
    owner_id NUMBER, -- ID-ul stăpânului (FK către tabela users)
    latitude NUMBER(10, 8),
    longitude NUMBER(11, 8),
    CONSTRAINT fk_pets_to_users FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE adoptions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER, -- referință la tabela pets
    adopter_id NUMBER, -- referință la tabela users
    adoption_date DATE DEFAULT SYSDATE,
    status VARCHAR2(10) CHECK (status IN ('pending', 'approved', 'rejection')),
    CONSTRAINT fk_adopted_pet FOREIGN KEY (pet_id) REFERENCES pets(id),
    CONSTRAINT fk_adopter FOREIGN KEY (adopter_id) REFERENCES users(id)
);

CREATE TABLE feeding_schedule (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER, -- referință la tabela pets
    time TIMESTAMP DEFAULT SYSDATE, -- ora programării mesei
    food_description VARCHAR2(255), -- descrierea alimentului
    frequency VARCHAR2(10) CHECK (frequency IN ('Daily', 'Weekly', 'Occasional')),
    CONSTRAINT fk_feeding_schedule FOREIGN KEY (pet_id) REFERENCES pets(id)
);

CREATE TABLE restrictions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER, -- referință la tabela pets
    description VARCHAR2(1000), -- descrierea restricției
    CONSTRAINT fk_restrictions FOREIGN KEY (pet_id) REFERENCES pets(id)
);

CREATE TABLE media (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER, -- referință la tabela pets
    type VARCHAR2(10) CHECK (type IN ('photo', 'video')),
    url VARCHAR2(255), -- adresa URL a fișierului media
    upload_date DATE DEFAULT SYSDATE, -- data încărcării fișierului media
    CONSTRAINT fk_media FOREIGN KEY (pet_id) REFERENCES pets(id)
);

CREATE TABLE medical_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER, -- referință la tabela pets
    record_date DATE DEFAULT SYSDATE, -- data înregistrării istoricului medical
    description VARCHAR2(1000), -- descrierea istoricului medical
    first_aid_method VARCHAR2(255), -- metoda de prim ajutor aplicată
    CONSTRAINT fk_medical_history FOREIGN KEY (pet_id) REFERENCES pets(id)
);

CREATE TABLE rss_feed (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL, -- titlul postării RSS
    content VARCHAR2(4000), -- conținutul postării RSS
    date_posted DATE DEFAULT SYSDATE, -- data postării RSS
    pet_id NUMBER, -- referință la tabela pets
    location VARCHAR2(255), -- locația unde se întâmplă evenimentul
    popularity_score NUMBER(3, 2), -- scorul de popularitate (de exemplu, între 0 și 10.00)
    is_general_news NUMBER(1) DEFAULT 0, -- 0 = nu este știre generală, 1 = este știre generală
    CONSTRAINT fk_rss_feed FOREIGN KEY (pet_id) REFERENCES pets(id)
);


SELECT * FROM system.users;
