DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE pets CASCADE CONSTRAINTS;
DROP TABLE adoptions CASCADE CONSTRAINTS;
DROP TABLE feeding_schedule CASCADE CONSTRAINTS;
DROP TABLE restrictions CASCADE CONSTRAINTS;
DROP TABLE media CASCADE CONSTRAINTS;
DROP TABLE medical_history CASCADE CONSTRAINTS;
DROP TABLE rss_feed CASCADE CONSTRAINTS;



ALTER TABLE pets DROP CONSTRAINT fk_pet_id;
ALTER TABLE adoptions DROP CONSTRAINT fk_pet_id;
ALTER TABLE adoptions DROP CONSTRAINT fk_adopter_id;
ALTER TABLE feeding_schedule DROP CONSTRAINT fk_pet_id;
ALTER TABLE restrictions DROP CONSTRAINT fk_pet_id;
ALTER TABLE media DROP CONSTRAINT fk_pet_id;
ALTER TABLE medical_history DROP CONSTRAINT fk_pet_id;
ALTER TABLE rss_feed DROP CONSTRAINT fk_pet_id;
